GET http://localhost:3000/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImludmFsaWRAaW52YWxpZC5pbnZhbGlkIiwiaWF0IjoxNjk2Njc4NjEyLCJleHAiOjE2OTY2ODIyMTJ9.5vJCBvvFH9vDU47za4MdLBpAEeIZZjYaKxEUmaZkOb0